name: Connect GitHub Actions to GCP

on:
  workflow_dispatch:

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_PROJECT_NUMBER: ${{ secrets.GCP_PROJECT_NUMBER }}

permissions:
  id-token: write
  contents: read
jobs:
  gcp:
    runs-on: ubuntu-latest
    steps:
      - id: clone
        name: Checkout project
        uses: actions/checkout@v4
      - id: authenticate
        name: Configure GCP credentials
        uses: google-github-actions/auth@v2
        with:
          create_credentials_file: true
          workload_identity_provider: projects/${{ env.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-oidc-provider
          service_account: github-actions
      - id: info
        name: Get information from GCP credentials
        run: |
          gcloud info
