name: Development Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - id: 'setup'
      name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - id: 'info'
      name: 'Use gcloud CLI'
      run: 'gcloud info'
